version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "2137:2137"
    volumes:
      - ./backend/data:/app/data  

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
